- block:
    - snort_rule:
        rule: "{{ ids_rule }}"
        state: "{{ ids_rule_state }}"
        rules_file: "{{ ids_rules_file|default('/etc/snort/rules/local.rules') }}"
      notify: restart snort
  collections:
    - ansible_security.community
