### requried
# this can be a company/brand or product namespace under which all content lives
namespace: ansible_security
# the designation of this specific collection
name: collection
# semantic versioning compliant version designation
version: 0.0.1
# a list of the collection's content authors: 'Full Name <email> (http://site) @nicks:irc/im/site#channel'
authors:
  - 'Ansible Security Automation Team (https://github.com/ansible-security)'

### optional but strongly advised
# short summary of the collection
description: Ansible Collection of content aiming to automate common tasks of Information Security Professionals for various software/services/appliances
# a valid SPDX license identifier https://spdx.org/licenses/
license:
  - 'GPL-3.0-or-later'
# list of keywords you want to associate the collection with for indexing/search systems
tags:
  - security
# list of dependencies, other collections this collection requires to be installed for it to be usable
#dependencies:

### urls
# url of originating SCM repository
repository: 'https://github.com/ansible-security/security_collection'
# url to online docs
documentation: 'https://github.com/ansible-security/security_collection'
# homepage of the collection/project
homepage: 'https://github.com/ansible-security/security_collection'
# issue tracker url
issues: 'https://github.com/ansible-security/security_collection/issues'
