---

- name: apply config template for snort provider
  template:
    src: snort.conf.j2
    dest: /etc/snort/snort.conf
  notify: restart snort

- name: handle remote logging if/when necessary
  block:
    - name: apply rsyslog config
      template:
        src: ids_confg_snort_rsyslog.conf.j2
        dest: /etc/rsyslog.d/ids_confg_snort_rsyslog.conf
      notify:
        - restart rsyslog

  when: (ids_config_remote_log is defined) and ids_config_remote_log

